- hosts: all
  gather_facts: yes
  become: yes
  vars:
    motd_content_centos: "This is centos message of day\n"
    motd_content_ubuntu: "This is ubuntu message of day"
  tasks:
    - name: copy this file content to /etc/motd
      copy:
       content: "{{ motd_content_centos }}"
       dest: /etc/motd
      when: ansible_distribution == "CentOS"
