### In this playbook, i was trying to get all facts for host. Intrestingly, as defined earlier in other playbook, we need to have gather_facts true so as to use magic variable hostvars. Interstingly, besides that you may be surprised why msg is working and var is not working in debug module. Reason, is var just displays defined variable and here we didn't have any defined varible with hostvars. msg gets that value.. Need to research how...For future references, these are git source controlled


- hosts: one
  gather_facts: true
  
  tasks:
    - name: display that fact value
      debug:
        #var: stored_value
        msg: "{{ hostvars[inventory_hostname] }}"
        #var: "{{ hostvars[inventory_hostname] }}"
      register: data

##### Displaying data variable we captured from above
    - name: display data value
      debug:
        var: data
