#### In this playbook, i was testing how we use hostvars and set_fact. So, to use hostvars, we have keep gather_facts as yes and set_fact is similar to varibles, but more dynamically we can set them. Beauty of set_facts. Firstly, if you getting errors always see what data is being returned. I was using last message statement in last line and then i realized data is what we have from that returned call. So, dont worry if those calls return no object found. If you want to see all facts availble in hostvars hash, just use last msg statement and then capture that output and then traverse accordingly. 

# I used this command ansible adhoc command ansible one -i list -m setup and realized how facts info was categorized. so, we are using correctly as from data that is retruned fromt that facts output. See f.yml also to know difference between attribute var and msg in debug module. To get any other facts info, i would suggest first see what data is returned using posted adhoc command and then use json formatter online https://jsonformatter.curiousconcept.com/ to get yourself idealized how that json data is formatted.That makes life so easier. For future uses, i am source controlling this under git@github.com:praveenreddy544/ansible_repo.git. Clone this repo and you can see this stuff. creds for github are praveenreddy544 and pwd is default one u know ending in .....369

- hosts: one
  gather_facts: true
  
  tasks:
    - name: get that fact value
      setup:
        filter: ansible_architecture

    - name: set that fact value
      set_fact:
        stored_value: "{{ ansible_architecture }}"
      #debug: {{ hostvars[inventory_name]['ansible_bios_date'] }}
    - name: display that fact value
      debug:
        #var: stored_value
        msg: "defined value is {{ stored_value }}"

    - name: display directory from hostvars hash
      debug:
        #msg: "value is  {{ hostvars[inventory_hostname]['ansible_facts']['ansible_bios_date'] }} "
        #msg: "value is  {{ hostvars[inventory_hostname]['ansible_distribution_version'] }}"
        #msg: "value is  {{ hostvars[inventory_hostname]['ansible_env']['ansible_default_ipv4'] }}"
        #msg: "value is  {{ hostvars[inventory_hostname]['ansible_env'] }}"
        #msg: "value is  {{ hostvars[inventory_hostname]['ansible_hostname'] }}"
        msg: "value is  {{ hostvars[inventory_hostname]['ansible_cmdline']['BOOT_IMAGE'] }}"
