- hosts: one
  gather_facts: no
  become: yes
  tasks:
    - name: copy sudoers template file to preserve
      template:
        src: templates/sudoers_file.j2
        dest: /etc/sudoers
        owner: root
        group: root
        mode: '0440'
        backup: yes
        validate: /usr/sbin/visudo -cf %s
        selevel: _default
        serole: _default
        setype: _default
      notify: run this task as defined

    - name: run this task as defined
      command: /usr/sbin/dmidecode
      register: dmidecode_run_data

    - name: display dmidecode_run_data var
      debug: 
        var: dmidecode_run_data
